Домашнее задание «Функции и работа с данными»

Задание 1**
Напишите функцию, которая классифицирует фильмы из материалов занятия по следующим правилам:
- оценка 2 и меньше - низкий рейтинг
- оценка 4 и меньше - средний рейтинг
- оценка 4.5 и 5 - высокий рейтинг

Результат классификации запишите в столбец class

In [1]:
import pandas as pd

In [2]:
ratings_df = pd.read_csv('ratings.csv')

movies_df = pd.read_csv('movies.csv')

def get_rated_films_df(ratings_df, movies_df):
    def get_class(row):
        if row['rating'] <= 2:
            return 'low'
        elif row['rating'] <= 4.5:
            return 'medium'
        else:
            return 'high'
    
    result_df = ratings_df[['movieId', 'rating']].groupby('movieId').mean().reset_index()
    result_df['class'] = result_df.apply(get_class, axis=1)
    result_df = result_df.merge(movies_df, how='left', on='movieId')
    return result_df[['movieId', 'title', 'rating', 'class']]

get_rated_films_df(ratings_df, movies_df)

,movieId,title,rating,class
0,1,Toy Story (1995),3.872470,medium
1,2,Jumanji (1995),3.401869,medium
2,3,Grumpier Old Men (1995),3.161017,medium
3,4,Waiting to Exhale (1995),2.384615,medium
4,5,Father of the Bride Part II (1995),3.267857,medium
...,...,...,...,...
9061,161944,The Last Brickmaker in America (2001),5.000000,high
9062,162376,Stranger Things,4.500000,medium
9063,162542,Rustom (2016),5.000000,high
9064,162672,Mohenjo Daro (2016),3.000000,medium
9065,163949,The Beatles: Eight Days a Week - The Touring Y...,5.000000,high

Задание 2 Используем файл keywords.csv.

Необходимо написать гео-классификатор, который каждой строке сможет выставить географическую принадлежность определенному региону. Т. е. если поисковый запрос содержит название города региона, то в столбце 'region' пишется название этого региона. Если поисковый запрос не содержит названия города, то ставим 'undefined'.

Правила распределения по регионам Центр, Северо-Запад и Дальний Восток:

In [6]:
geo_data = {
    'Центр': ['москва', 'тула', 'ярославль'],
    'Северо-Запад': ['петербург', 'псков', 'мурманск'],
    'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']
}

keywords_df = pd.read_csv('keywords.csv')
#keywords_df.info()
#keywords_df

def get_region(row):
    for region, cities in geo_data.items():
        for city in cities:
            if city in row['keyword']:
                return region
    return None

keywords_df['region'] = keywords_df.apply(get_region, axis=1)
#keywords_df
keywords_df[pd.notnull(keywords_df['region'])]

                                     keyword   shows          region
127                             авито москва  979292           Центр
370                 авито ру санкт петербург  425134    Северо-Запад
564                погода в санкт петербурге  292489    Северо-Запад
849                          авито ярославль  209581           Центр
1063                     фарпост владивосток  176951  Дальний Восток
...                                      ...     ...             ...
99590  авито ярославль автомобили с пробегом    3673           Центр
99634   северпост новости мурманской области    3606    Северо-Запад
99808      полармед мурманск запись на прием    3719    Северо-Запад
99890                    яндекс метро москва    4548           Центр
99922                      авто ру ярославль    3712           Центр

[747 rows x 3 columns]